// <auto-generated />
namespace PS2._Practica_Semanal_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(status));
        
        string IMigrationMetadata.Id
        {
            get { return "202005222357060_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
